baseUrl = "https://eduardoweiland.info/"
title = "Eduardo Weiland"
theme = "hugo-coder"

paginate = 10

languageCode = "pt-br"
defaultContentLanguage = "pt-br"

pygmentsStyle = "dracula"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
    author = "Eduardo Weiland"
    info = "Fullstack Web Developer & Maker"
    description = "Blog de Eduardo Weiland"
    keywords = "blog,home,portfolio,personal,developer,maker"
    since = 2011

    avatarUrl = "images/avatar.png"
    favicon_32 = "images/favicon32.png"
    favicon_16 = "images/favicon16.png"

    colorScheme = "auto"

[[params.social]]
    name = "GitHub"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/eduardoweiland/"

[[params.social]]
    name = "GitLab"
    icon = "fa fa-gitlab"
    weight = 2
    url = "https://gitlab.com/eduardoweiland/"

[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/eduardoweiland/"

[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 4
    url = "/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    author = "authors"

[permalinks]
    posts = "/blog/:year/:month/:title/"

# Content-Security-Policy
[params.csp]
    childsrc = ["'self'"]
    fontsrc = ["'self'"]
    formaction = ["'self'"]
    framesrc = ["'self'"]
    imgsrc = ["'self'"]
    objectsrc = ["'none'"]
    stylesrc = [ "'self'", "'unsafe-inline'"]
    scriptsrc = ["'self'", "'unsafe-inline'"]
    prefetchsrc = ["'self'"]
    connectsrc = ["'self'"]
